gText_Birch_Welcome::
	.string "Sorry to call you on short notice!\p"
	.string "I'm STEVEN, former Hoenn Champion.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "The POKéMON LEAGUE has entrusted\n"
	.string "you with an important task.\p{PAUSE 96}"
	.string "$"

gText_Birch_MainSpeech::
	.string "There is a place far from Hoenn\n"
	.string "called Tianlan Island.\p"
	.string "Last week, we received reports\n"
	.string "of anomalous weather on the island.\p"
	.string "Something terrible might have\n"
	.string "happened there!\p"
	.string "I understand you have only just\n"
	.string "become a LEAGUE REPRESENTATIVE…\p"
	.string "But you are the nearest person\n"
	.string "who can help out.\p$"

gText_Birch_AndYouAre::
	.string "Oh, but I never asked…$"

gText_Birch_BoyOrGirl::
	.string "What do you look like?$"

gText_Birch_WhatsYourName::
	.string "And what is your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Got it.\p"
	.string "You're representative {PLAYER}{KUN},\n"
	.string "currently on your way to Tianlan Island.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Investigate the island, and find out\n"
	.string "What is happening to the place.\p"
	.string "Oh, and...\p"
	.string "This is a dangerous task, so\l"
	.string "I have arranged something for you.\n"
	.string "Look for a bag in your boat cabin.\p"
	.string "$"
