gText_Birch_Welcome::
	.string "Sorry to call you on short notice!\p"
	.string "I'm STEVEN, former Hoenn Champion.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "The POKéMON LEAGUE has entrusted\n"
	.string "you with an important task.\p{PAUSE 96}"
	.string "$"

gText_Birch_MainSpeech::
	.string "There is a place far away\n"
	.string "called Tianlan Island.\p"
	.string "The POKéMON LEAGUE maintains a few\n"
	.string "POKéMON GYMS there.\p"
	.string "However, since a few weeks ago,\l"
	.string "We couldn't get in contact with\n"
	.string "Anyone on the island.\p"
	.string "Something terrible might have\n"
	.string "happened there!\p"
	.string "I understand you have only just\n"
	.string "become a LEAGUE REPRESENTATIVE...\p"
	.string "But you are the closest person\n"
	.string "who can help out.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Oh, but I never asked about you!$"

gText_Birch_BoyOrGirl::
	.string "What do you look like?$"

gText_Birch_WhatsYourName::
	.string "And what is your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Got it.\p"
	.string "You're representative {PLAYER}{KUN},\n"
	.string "currently on your way to Tianlan Island.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Investigate the island, and find out\n"
	.string "What is happening to the place.\p"
	.string "A good place to start looking at\n"
	.string "might be the POKéMON GYMS.\p"
	.string "Oh, and...\p"
	.string "Look for a briefcase on the boat.\p"
	.string "This is a dangerous task, so\n"
	.string "I have arranged something for you.\p"
	.string "$"
