SkywardTrail_Lab_B1_MapScripts::
	.byte 0

SkywardTrail_Lab_B1_Text_ScientistAskGetResearch:
	.string "Oh, fiddlesticks…\p"
	.string "TEAM AQUA messed with the control\n"
	.string "panel, and now it's all dark!\p"
	.string "If we don't fix the settings, the\n"
	.string "power generator is going to overload\l"
	.string "and explode in…… about 4 years!\p"
	.string "What's more, all my research is stored\n"
	.string "on the computers that I can't use!\p"
	.string "You're a trainer, right?\n"
	.string "Can you go kick some TEAM AQUA a-\n"
	.string "I mean, kindly repair what they have\l"
	.string "tampered with?\p"
	.string "All you have to do is step on the big\n"
	.string "RED RESET BUTTON to the north of here.\p"
	.string "The hooligans have activated our\n"
	.string "security gates, so you need to find the\l"
	.string "buttons to open those as well.\p"
	
SkywardTrail_Lab_B1_Text_ScientistRepeat:
	.string "Were you able to find the RED RESET BUTTON?\n"
	.string "It is to the north of here.\p"
	.string "You may have to open some of those security\n"
	.string "gates first with the colored buttons.$"
	
SkywardTrail_Lab_B1_Text_ScientistComplete:
	.string "Yes! You showed them what for!\p"
	.string "Let me check the status of the generator.\p"
	.string "Hmm, it looks like it will now overload\n"
	.string "in one year! An amazing improvement-\l"
	.string "Wait, that's bad.\p"
	.string "I must hurry back and resolve that, but\n"
	.string "do accept this reward for your efforts!$"
	
SkywardTrail_Lab_B1_Text_ScientistExplain:
	.string "This is a battle item for your "