ShuiyunTown_House2_MapScripts::
	.byte 0


ShuiyunTown_House2_EventScript_Camper::
	msgbox ShuiyunTown_House2_Text_Camper, MSGBOX_NPC
	end

ShuiyunTown_House2_EventScript_LittleBoy::
	msgbox ShuiyunTown_House2_Text_LittleBoy, MSGBOX_NPC
	end

ShuiyunTown_House2_Text_Camper:
	.string "The secret to being a good TRAINER\n"
	.string "is having a party of POKéMON whose\l"
	.string "types complement each other.\p"
	.string "If your POKéMON share a weakness,\n"
	.string "that weakness will be exploited!\p"
	.string "Our family loves EEVEE, as you can\n"
	.string "evolve it to whatever type needed\l"
	.string "for your party.$"

ShuiyunTown_House2_Text_LittleBoy:
	.string "EEVEE is a unique POKéMON!\n"
	.string "It has many evolutions with\l"
	.string "different types!\p"
	.string "All you have to do is find\n"
	.string "the right evolution stone,\l"
	.string "and give it to EEVEE!\p"
	.string "Some EEVEE evolutions need\n"
	.string "a certain time of day,\l"
	.string "but using SUN STONE or MOON\l"
	.string "STONE is close enough, I say!$"